version: '1'

services:
  webapi:
    image: webapi
    container_name: webapiapp
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mybridgenetwork
    ports:
      - 8080:8080
    expose:
      - 8080


  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=Secret12345!
      - POSTGRES_DB=mydatabase
    networks:
      - mybridgenetwork
    ports:
      - 5432:5432
    volumes:
      - mydatabasevolume:/var/lib/postgresql/data
    expose:
      - 5432

  redis: 
    image: redis
    container_name: redisdb
    networks:
      - mybridgenetwork
    ports:
      - 6379:6379
    expose:
      - 6379

networks:
  mybridgenetwork:
    driver: bridge

volumes:
  mydatabasevolume: